brew "stow"
brew "asdf"
brew "ripgrep"
brew "lazygit"
brew "glow"
brew "tmux"
brew "zoxide"
brew "fzf"
brew "starship"
brew "gpg"
brew "flyctl"
brew "markdownlint-cli"
brew "fd"
brew "yazi"
brew "atuin"
brew "pandoc"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "nushell"

# YW
brew "imagemagick"
brew "ghostscript"
brew "libyaml"

# Postgres
brew "gcc"
brew "readline"
brew "zlib"
brew "curl"
brew "ossp-uuid"
brew "icu4c"
brew "pkg-config"
brew "openssl"


cask "slack"
cask "1password"
cask "twingate"
cask "alacritty"
cask "raycast"
cask "whatsapp"
cask "signal"
cask "google-chrome"
cask "tableplus"
cask "shottr"
cask "synology-drive"
cask "flux"
cask "ollama"
cask "notion"
cask "font-hack-nerd-font"
cask "font-fira-code-nerd-font"
cask "basictex"
cask "docker"
cask "dash"

# MAS
mas "Numbers", id: 409203825
